#!/usr/bin/env bash
# Displays information about subdomains.

# Variables & parameters
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

dig_cmd() {
    local sub="$1"
    local INFO=$(dig "${sub}.${domain}" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
    local IP=$(echo "$INFO" | awk '{print $5}')
    local RECORD=$(echo "$INFO" | awk '{print $4}')

    echo "The subdomain ${sub} is a ${RECORD} record and points to ${IP}"
}

if [ $# -eq 1 ]; then
    for subs in "${subdomains[@]}"; do
        dig_cmd "$subs"
    done
elif [ $# -eq 2 ]; then
    dig_cmd "$sub"
fi
