#!/usr/bin/env bash
# Script to display information about subdomains.

# Function to display subdomain information
display_subdomain_info() {
    local subdomain="$1"
    local domain="$2"
    local info=$(dig +short -t A "${subdomain}.${domain}")
    
    if [ -n "$info" ]; then
        echo "The subdomain ${subdomain} is an A record and points to ${info}"
    else
        echo "The subdomain ${subdomain} does not have an A record"
    fi
}

# Main script logic
if [ "$#" -eq 0 ]; then
    echo "Usage: $0 domain [subdomain]"
    exit 1
fi

domain="$1"
sub="$2"

if [ -z "$sub" ]; then
    subdomains=("www" "lb-01" "web-01" "web-02")
    for subdomain in "${subdomains[@]}"; do
        display_subdomain_info "$subdomain" "$domain"
    done
else
    display_subdomain_info "$sub" "$domain"
fi
