#!/usr/bin/env bash
# Displays information about subdomains.

# Variables & parameters
subdomains=("www" "lb-01" "web-01" "web-02")
domain="$1"
sub="$2"

# Function to display subdomain information
display_subdomain_info() {
    local subdomain="$1"
    local domain="$2"
    local info=$(dig "${subdomain}.${domain}" | grep -A1 'ANSWER SECTION:' | awk 'NR==2')
    local ip=$(echo "$info" | awk '{print $5}')
    local record=$(echo "$info" | awk '{print $4}')

    echo "The subdomain ${subdomain} is a ${record} record and points to ${ip}"
}

# Main script logic
if [ $# -eq 1 ]; then
    for subdomain in "${subdomains[@]}"; do
        display_subdomain_info "$subdomain" "$domain"
    done
elif [ $# -eq 2 ]; then
    display_subdomain_info "$sub" "$domain"
fi
