#!/usr/bin/env bash

# Update the system and install necessary packages
sudo apt-get update
sudo apt-get install software-properties-common
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install certbot haproxy nginx

# Obtain the SSL certificate
sudo certbot certonly --standalone -d www.aiglow.tech --preferred-challenges http -m nkugwamarkwilliam@gmail.com --agree-tos --no-eff-email

# Update the HAProxy configuration
sudo bash -c "cat > /etc/haproxy/haproxy.cfg << EOL
global
    log /dev/log local0
    log /dev/log local1 notice
    chroot /var/lib/haproxy
    stats socket /run/haproxy/admin.sock mode 660 level admin expose-fd listeners
    stats timeout 30s
    user haproxy
    group haproxy
    daemon

defaults
    log global
    mode http
    option httplog
    option dontlognull
    timeout connect 5000
    timeout client  50000
    timeout server  50000
    errorfile 400 /etc/haproxy/errors/400.http
    errorfile 403 /etc/haproxy/errors/403.http
    errorfile 408 /etc/haproxy/errors/408.http
    errorfile 500 /etc/haproxy/errors/500.http
    errorfile 502 /etc/haproxy/errors/502.http
    errorfile 503 /etc/haproxy/errors/503.http
    errorfile 504 /etc/haproxy/errors/504.http

frontend http-in
    bind *:80
    bind *:443 ssl crt /etc/letsencrypt/live/www.aiglow.tech/fullchain.pem key /etc/letsencrypt/live/www.aiglow.tech/privkey.pem
    mode http
    http-request redirect scheme https if !{ ssl_fc }
    default_backend servers

backend servers
    mode http
    balance roundrobin
    option forwardfor
    http-response set-header X-Served-By %[req.hdr(host)]
    server 172004-web-01 54.157.136.99 check
    server 172004-web-02 54.173.109.63 check
EOL"

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy

# Update the Nginx configuration on web servers
for ip in "54.157.136.99" "54.173.109.63"; do
    ssh ubuntu@$ip "
    sudo sed -i 's|root /var/www/html;|return 200 \"Holberton School\n\";|g' /etc/nginx/sites-available/default;
    sudo systemctl restart nginx;
    "
done
