#!/usr/bin/env bash

# Update the HAProxy configuration to redirect HTTP to HTTPS
sudo bash -c "cat >> /etc/haproxy/haproxy.cfg << EOL

frontend http-in
    bind *:80
    mode http
    redirect scheme https code 301 if !{ ssl_fc }
    default_backend servers

EOL"

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy
