#!/usr/bin/env bash
# Install Nginx
apt-get update
apt-get -y install nginx

# Configure Nginx to listen on port 80 and return "Hello World!"
echo "Hello World!" > /var/www/html/index.html
sed -i 's/80 default_server/80/' /etc/nginx/sites-available/default
sed -i 's|# server_name _;|root /var/www/html;\n        index index.html;\n        server_name _;|' /etc/nginx/sites-available/default

# Restart Nginx
/usr/sbin/service nginx reload
