#!/usr/bin/env bash
#!/bin/bash
sudo apt-get update
sudo apt-get install -y nginx

sudo bash -c 'cat << EOF > /etc/nginx/sites-available/redirection
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;
    location /redirect_me {
        return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
    }
}
EOF'

sudo ln -s /etc/nginx/sites-available/redirection /etc/nginx/sites-enabled/
sudo rm /etc/nginx/sites-enabled/default

sudo service nginx restart
