#!/bin/bash

# Update package repository and install Nginx
sudo apt-get update
sudo apt-get install nginx -y

# Copy Nginx configuration from web-01 to web-02
sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bak
sudo scp ubuntu@[STUDENT_ID]-web-01:/etc/nginx/sites-available/default /etc/nginx/sites-available/

# Modify Nginx configuration to include custom header
sudo sed -i '/^        location \/ {$/a         add_header X-Served-By $hostname;' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo systemctl restart nginx
