#!/usr/bin/env bash

# Install and configure HAProxy on lb-01 server

# Update the package list and install HAProxy
sudo apt-get update
sudo apt-get install -y haproxy

# Create a backup of the default configuration file
sudo cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy.cfg.backup

# Generate the new configuration file
cat <<EOF | sudo tee /etc/haproxy/haproxy.cfg > /dev/null
defaults
    mode http
    timeout client 10s
    timeout server 10s
    timeout connect 10s

frontend http-in
    bind *:80
    default_backend webservers

backend webservers
    balance roundrobin
    option httpchk
    server web-01 [STUDENT_ID]-web-01:80 check
    server web-02 [STUDENT_ID]-web-02:80 check
EOF

# Enable HAProxy to be managed as a service
sudo systemctl enable haproxy.service

# Restart HAProxy to apply the changes
sudo systemctl restart haproxy.service
