#!/usr/bin/env bash
##########################################################
# Script: MySQL Backup and Compression
# Description: This script performs a MySQL database backup and compresses it into a tar.gz archive.
# Author: Your Name
##########################################################

# Check if password is supplied
if [ $# -ne 1 ]; then
    echo "Usage: $0 <mysql root password>"
    exit 1
fi

# MySQL root password
password="$1"

# Get date elements
day=$(date +%d)
month=$(date +%m)
year=$(date +%Y)

# MySQL dump filename
dump_file="backup.sql"

# Archive filename
archive_file="${day}-${month}-${year}.tar.gz"

# Dump all databases
mysqldump -u root -p"${password}" --all-databases > "${dump_file}"

# Compress the dump file into a tar.gz archive
tar -czvf "${archive_file}" "${dump_file}" >/dev/null 2>&1

# Check if compression was successful
if [ $? -eq 0 ]; then
    echo "Backup successfully created and compressed: ${archive_file}"
    # Remove the dump file
    rm "${dump_file}"
else
    echo "Backup compression failed."
    # Remove the dump file and incomplete archive
    rm "${dump_file}" "${archive_file}"
    exit 1
fi

